#### GET / 

GET http://localhost:5000

#### Register a user Post /auth/register
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username":"gelgamish@gmail.com",
    "password":"msa masa mosa "
}

#### login a user Post /auth/login 
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username":"gelgamish@gmail.com",
    "password":"msa masa mosa "
}

